// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/books": {
            "post": {
                "description": "管理员添加图书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/books"
                ],
                "summary": "新增图书",
                "parameters": [
                    {
                        "description": "书名",
                        "name": "bookName",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "作者",
                        "name": "author",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "出版社",
                        "name": "publishingHouse",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "译者",
                        "name": "translator",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "发行时间",
                        "name": "publishDate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "页数",
                        "name": "pages",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "ISBN号码",
                        "name": "ISBN",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "价格",
                        "name": "price",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "内容简介",
                        "name": "briefIntroduction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "作者简介",
                        "name": "authorIntroduction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "封面地址",
                        "name": "imgUrl",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "删除标识",
                        "name": "delFlg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "图书数量",
                        "name": "count",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "图书种类id",
                        "name": "categoryId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/admin/books/{id}": {
            "put": {
                "description": "管理员修改图书",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/books"
                ],
                "summary": "修改图书",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "图书id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "书名",
                        "name": "bookName",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "作者",
                        "name": "author",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "出版社",
                        "name": "publishingHouse",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "译者",
                        "name": "translator",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "发行时间",
                        "name": "publishDate",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "页数",
                        "name": "pages",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "ISBN号码",
                        "name": "ISBN",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "价格",
                        "name": "price",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "内容简介",
                        "name": "briefIntroduction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "作者简介",
                        "name": "authorIntroduction",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "封面地址",
                        "name": "imgUrl",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "删除标识",
                        "name": "delFlg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "图书数量",
                        "name": "count",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "图书种类id",
                        "name": "categoryId",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "管理员删除图书",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/books"
                ],
                "summary": "管理员删除图书",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "书籍id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/admin/categories": {
            "post": {
                "description": "添加分类信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/categories"
                ],
                "summary": "添加分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分类名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/admin/categories/{id}": {
            "get": {
                "description": "管理员获取某个分类信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/categories"
                ],
                "summary": "管理员获取某个分类信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/libraryManagementSystem_appV2_model.Category"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "更新分类信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/categories"
                ],
                "summary": "更新分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "分类名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除分类信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/categories"
                ],
                "summary": "删除分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/admin/librarian/logout": {
            "get": {
                "description": "会执行图书管理员退出登录操作",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "图书管理员退出登录",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/admin/records/{status}": {
            "get": {
                "description": "获取图书馆所有的借/还记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/records"
                ],
                "summary": "获取所有借/还记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "标记是否归还字段",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/libraryManagementSystem_appV2_model.Record"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/users": {
            "get": {
                "description": "搜索获取用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/users"
                ],
                "summary": "搜索用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前页",
                        "name": "currentPage",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页大小",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "userName",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户姓名",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/libraryManagementSystem_appV2_model.User"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/users/{id}": {
            "get": {
                "description": "管理员获取用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/users"
                ],
                "summary": "管理员获取用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/libraryManagementSystem_appV2_model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "管理员更新用户信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/users"
                ],
                "summary": "更新用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "userName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "电话",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "用户帐号状态",
                        "name": "status",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}/records": {
            "get": {
                "description": "获取用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/users"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/libraryManagementSystem_appV2_model.Record"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/admin/users/{id}/records/{status}": {
            "get": {
                "description": "获取某个用户的借/还记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/users"
                ],
                "summary": "获取用户借/还记录",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "标记是否归还字段",
                        "name": "status",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/libraryManagementSystem_appV2_model.Record"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/adminLogin": {
            "post": {
                "description": "会执行图书管理员登录操作",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "图书管理员登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "userName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/books": {
            "get": {
                "description": "获取所有图书或者搜索图书",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "搜索图书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前页",
                        "name": "currentPage",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页大小",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "书籍编号",
                        "name": "ISBN",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "图书名称",
                        "name": "bookName",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/tools.Page-model_BookInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/books/{id}": {
            "get": {
                "description": "获取一个图书的信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "获取图书信息",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "书籍id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.BookInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "搜索获取分类信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "搜索分类",
                "parameters": [
                    {
                        "type": "string",
                        "description": "当前页",
                        "name": "currentPage",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "页大小",
                        "name": "pageSize",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "查询条件",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/tools.Page-libraryManagementSystem_appV2_model_Category"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/getCode": {
            "get": {
                "description": "用户登录页获取验证码操作",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "登录验证码",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/user/users": {
            "get": {
                "description": "获取用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/users"
                ],
                "summary": "用户查看信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/libraryManagementSystem_appV2_model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "用户修改自己的信息",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/users"
                ],
                "summary": "用户修改信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "userName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "旧密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "新密码",
                        "name": "newPassword",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "电话",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/user/users/messages": {
            "get": {
                "description": "获取用户收件箱信息(这个接口获取消息没有什么意义，只是提示有书没还)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/users"
                ],
                "summary": "用户收件箱",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/user/users/records": {
            "get": {
                "description": "获取用户所有记录或者借/还记录",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/users"
                ],
                "summary": "用户获取所有记录或者借/还记录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "是否归还",
                        "name": "status",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/libraryManagementSystem_appV2_model.Record"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/user/users/records/{bookId}": {
            "post": {
                "description": "用户借书",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/books"
                ],
                "summary": "用户借书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "书籍id",
                        "name": "bookId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/user/users/records/{id}": {
            "put": {
                "description": "用户还书",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user/books"
                ],
                "summary": "用户还书",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer 用户令牌",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "借书记录的id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/user/users/{id}": {
            "delete": {
                "description": "管理员通过id删除用户",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin/users"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "用户id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        },
        "/userLogin": {
            "post": {
                "description": "会执行用户登录操作",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "userName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码",
                        "name": "captcha",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "验证码的key",
                        "name": "captchaKey",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/libraryManagementSystem_appV2_logic.Token"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "用户注册或管理员添加用户",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "新增一个用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "userName",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "性名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "性别",
                        "name": "sex",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "电话",
                        "name": "phone",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/libraryManagementSystem_appV2_tools.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "libraryManagementSystem_appV1_logic.Token": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "libraryManagementSystem_appV1_model.Category": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "libraryManagementSystem_appV1_model.Record": {
            "type": "object",
            "properties": {
                "bookId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "overTime": {
                    "type": "string"
                },
                "returnTime": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "status": {
                    "description": "已归还1 未归还0",
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "libraryManagementSystem_appV1_model.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                },
                "status": {
                    "description": "` + "`" + `json:\"\"默认正常0 封禁1",
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "libraryManagementSystem_appV1_tools.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "libraryManagementSystem_appV2_logic.Token": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "libraryManagementSystem_appV2_model.Category": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "libraryManagementSystem_appV2_model.Record": {
            "type": "object",
            "properties": {
                "bookId": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "overTime": {
                    "type": "string"
                },
                "returnTime": {
                    "type": "string"
                },
                "startTime": {
                    "type": "string"
                },
                "status": {
                    "description": "已归还1 未归还0",
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "libraryManagementSystem_appV2_model.User": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "sex": {
                    "type": "string"
                },
                "status": {
                    "description": "` + "`" + `json:\"\"默认正常0 封禁1",
                    "type": "integer"
                },
                "userName": {
                    "type": "string"
                }
            }
        },
        "libraryManagementSystem_appV2_tools.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "model.Book": {
            "type": "object",
            "properties": {
                "bn": {
                    "type": "string"
                },
                "categoryId": {
                    "type": "integer"
                },
                "count": {
                    "description": "默认1",
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.BookInfo": {
            "type": "object",
            "properties": {
                "ISBN": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "authorIntroduction": {
                    "type": "string"
                },
                "bookName": {
                    "type": "string"
                },
                "briefIntroduction": {
                    "type": "string"
                },
                "categoryId": {
                    "type": "integer"
                },
                "count": {
                    "description": "默认1",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "pages": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "publishDate": {
                    "type": "string"
                },
                "publishingHouse": {
                    "type": "string"
                },
                "translator": {
                    "type": "string"
                }
            }
        },
        "tools.Page-libraryManagementSystem_appV2_model_Category": {
            "type": "object",
            "properties": {
                "currentPage": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "pages": {
                    "description": "总页数",
                    "type": "integer"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/libraryManagementSystem_appV2_model.Category"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        },
        "tools.Page-model_BookInfo": {
            "type": "object",
            "properties": {
                "currentPage": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "pages": {
                    "description": "总页数",
                    "type": "integer"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.BookInfo"
                    }
                },
                "total": {
                    "description": "总数",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "图书管理系统V1",
	Description:      "go图书管理系统",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
